create quiz home page
git-0r/quiz_screens pull request #1
Opened 2022-02-20 12:13 UTC by git-0r

# created home page screen for quiz app.
![quiz1](https://user-images.githubusercontent.com/68228131/154841843-4a16d26e-b7ec-48c4-b5f1-d1ce9dd03e4b.png)
![quiz2](https://user-images.githubusercontent.com/68228131/154841847-1f3a7845-7e71-4767-a8c8-8bda8d05af7b.png)

2022-02-20 12:57 UTC, manish-GH reviewed
The UI looks clean, it's even responsive. Nice work.

Just change the px to rem wherever possible and consider using the header tags

2022-02-20 12:57 UTC, manish-GH commented on index.html
> +        <p class="heading-lg">Popular Quiz</p>
You could probably use a header tag instead of p tag. Do this for other headings as well

2022-02-20 12:57 UTC, manish-GH commented on style.css
> +  height: 30px;
use rem

2022-02-20 12:57 UTC, manish-GH commented on style.css
> +  height: 350px;
use rem

2022-02-20 12:57 UTC, manish-GH commented on style.css
> +  left: 50px;
use rem

2022-02-20 12:57 UTC, manish-GH commented on style.css
> +  height: 30px;
use rem

2022-02-20 12:57 UTC, manish-GH commented on style.css
> +    height: 250px;
use rem

2022-02-20 12:57 UTC, manish-GH commented on style.css
> +    top: 20px;
use rem

2022-02-20 20:42 UTC, manish-GH approved these changes
I forgot to mention about the em for media queries. Just change that and you are good to merge

2022-02-20 20:42 UTC, manish-GH commented on style.css
> +@media screen and (max-width: 600px) {
You are supposed to use em for media queries

2022-02-21 13:53 UTC, varun1233 approved these changes
Code looks good. Ready to merge
Suggestion: It's a good practice to provide alt for images, in some places you are providing it but in some place you aren't. you can look into this

2022-02-21 14:02 UTC, Naman-Saxena1 requested changes

2022-02-21 14:02 UTC, Naman-Saxena1 commented on index.html
> +            <img class="banner-img"
You can use object-fit: cover on this class., rather than object-fit: fill

2022-02-21 14:07 UTC, gouravmarch20 approved these changes

2022-02-21 14:07 UTC, gouravmarch20 commented on style.css
> +  flex-wrap: wrap;
majority things are find great, flex-wrap: wrap; good to see you had used it

2022-02-21 15:45 UTC, merged